### ISSUE TITLE
Point out that *you* set up the continuous integration

### ISSUE THREAD

**Issue by cbeleites** [eoduniyi/hyperSpec.gsoc2020#12]
I think for week 2 you should point out that *you* set up  travis, appveyor and codecov for us. 

Perhaps it would be good to say already here that the starting point was a legacy Makefile system (that also ran some tests) to be used offline. And that part of the summer was to move from that system to online CI.

**Comment by eoduniyi** [comment]
On it!

**Comment by eoduniyi** [comment]
The last commit on the develop branch closes this issue.
