### ISSUE TITLE
List of code contributions/commits

### ISSUE THREAD

**Issue by cbeleites** [eoduniyi/hyperSpec.gsoc2020#13]
I think, it may be good to have a block at the beginning

# My commits during GSoC

- repo [cbeleites/hyperSpec](https://github.com/cbeleites/hyperSpec/commits?author=eoduniyi)
- repo [r-hyperspec/hySpc.skeleton](https://github.com/r-hyperspec/hySpc.skeleton/commits?author=eoduniyi)
- ...

to make clear that you fulfill the formal requirement of submitting all your contributions.

**Comment by eoduniyi** [comment]
Okay I will do this

**Comment by eoduniyi** [comment]
The last commit on the develop branch closes this issue...thank you, Claudia
